select *
from rule_in_engine r1, rule_freein_engine_sec r2
where r1.app_no = r2.app_no
      and r1.app_no in (31801033100693);

select *
from rule_in_engine r1
where r1.app_no in (31801033100693);
select *
from rule_in_engine r1
where r1.id = '2203188';
select *
from rule_in_engine_sec r2
where r2.id = '2203188';

select *
from
  (select
     max(r.create_time),
     r.*
   from rule_in_engine r
   where r.app_no in (31801033100693)
   group by r.app_no) t1, (
                            select
                              max(r.create_time),
                              r.*
                            from rule_in_engine_sec r
                            where r.app_no in (31801033100693)
                            group by r.app_no)
                          t2
where t1.app_no = t2.app_no;

;
select
  adjust_yyhq_bankcard       '线上产品进件输入.盈衍已开户银行卡与嗨钱绑定银行卡是否一致',
  adjust_dd_report,
  js_limit_amount,
  zjybjqdate_nowsqdatedays,
  worktime,
  zjf,
  zxlxr_incomisblack,
  zxlxr_incomisdelq,
  zxlxr_tem_littlephone,
  zjlxr_black_number,
  zjlxr_number,
  post,
  dd_id_iphone_number,
  graduate_date,
  total_amt,
  bankcode,
  yjq_loan_highest_amount,
  total_amt_paid,
  dd_closetravel_percent,
  ##yyn_refused,
  ''                         studystyle,
  education,
  ifxj_station,
  xdcp_id,
  nowprovince,
  dd_liveincxdz_number,
  nowcity,
  wm_ddnumber,
  ifzd_school,
  adjust_gjj_report,
  yy_limit_amount,
  adjust_new_bankcard,
  xl_limit_amount,
  xn_limit_amount,
  adjust_hyc_client,
  adjust_power,
  if_allday,
  hlblack,
  ifoldcust,
  kd_limit_amount,
  hyc_limit_amount,
  huarong_limit_amount,
  haierlimit_amount,
  ifoldcustlddd,
  dfs_limit_amount,
  retain_totai_bj,
  sfz_name_number,
  sfz_phone_number,
  t1.identityvalid_startdate identityvalidstartdate,
  t1.identityvalid_enddate   identityvalidenddate,
  t1.identity_no             identityno,
  t1.app_amt                 appamt,
  lxr_incomisblack,
  lxr_incomisdelq,
  qslxr_tem_littlephone,
  age,
  grade,
  nation,
  mfb_facresult,
  mfb_score_card,
  maxent_jin_channel,
  maxent_id_client_cfnum,
  t1.app_no                  appno,
  hitgdelqjd,
  ifdelq,
  yh_terms,
  craweducation,
  deqlzncnts,
  ##custtype,
  ifloan_yjq,
  jzqk,
  jinjian_channel,
  lxr2_incomisblack,
  lxr2_incomisdelq,
  lxr1_incomisblack,
  lxr1_incomisdelq,
  jjk_freedom_score,
  jjk_trends_score,
  jjk_cash_score,
  dexfyfxfx_recent_6M,
  jyjebzc_recent_3M,
  jjkconsumer_group_mark,
  jjk_risk_score,
  marry,
  hk_date_number,
  famprovince,
  black_inter_score,
  appprovince,
  appcity,
  dhhm_name_number,
  dhhm_sfz_number,
  ddalways_travel_city,
  ddtravel_total_number,
  ddsj_average,
  ddsj_resigndate,
  dd_iphone_sqxxsfyz,
  dd_iphone_sfsmrz,
  dd_iphone_id_number,
  dd_usetime,
  dd_name_sqxxsfyz,
  dd_idcard_sqxxsfyz,
  ddsj_czdjrname,
  dddyh_total_amt,
  dddyh_total_paid,
  pay_quantity,
  nopay_sm_qualinty,
  ifvip,
  dd_workincxdz_number,
  ## producttype,
  relate_enterprises,
  seven_day_vipnum,
  local_life_time,
  self_call_cnt,
  all_contact_night,
  contact_early_morning,
  sms_mth_cnt,
  real_max_time,
  sms_cnt,
  yunying_call_out_cnt,
  phone_stop_time,
  mf_adjust_challenger,
  js_ifloan_yjq,
  service_providers_number,
  service_call_number,
  fqzps_11,
  fqzps_10,
  fqzps_12,
  fqzps_09,
  fqzps_08,
  fqzps_07,
  fqzps_06,
  fqzps_05,
  fqzps_04,
  fqzps_03,
  fqzps_02,
  fqzps_01,
  xz_information,
  wd_black,
  sxgg_information,
  ss_information,
  all_information,
  ktgg_information,
  fygg_information,
  cp_information,
  bzxr_information,
  ajlc_information,
  zhima_score,
  td_score,
  td_ruleitem,
  phoneiftdblack,
  sfziftdblack,
  phoneifhyblack,
  sfzifhyblack,
  zx_tdcomcnts,
  sfzifzxblack,
  py_score,
  py_smyizhi,
  jxl_zdlxrinblack,
  phoneifjxlblack,
  ifhavejxl,
  sfzifjxlblack,
  jxl_zjloancomcnts,
  jxlzxqs_contact_1w,
  jxlzxqs_contact_1m,
  jxlzxqs_contact_3m,
  jxl_zxcontactcnt,
  jxlzxqs_6mon_callcnt,
  jxlzxqs_5mon_callcnt,
  jxlzxqs_4mon_callcnt,
  jxlzxqs_3mon_callcnt,
  jxlzxqs_2mon_callcnt,
  jxlzxqs_1mon_callcnt,
  isnewmobile,
  jxl_mobilesm,
  jxllxr_contact_1w,
  jxllxr_contact_1m,
  jxllxr_contact_3m,
  jxl_lxrcontactcnt,
  jxllxr_6mon_callcnt,
  jxllxr_5mon_callcnt,
  jxllxr_4mon_callcnt,
  jxllxr_3mon_callcnt,
  jxllxr_2mon_callcnt,
  jxllxr_1mon_callcnt,
  jxllxr2_contact_3m,
  jxl_lxr2contactcnt,
  jxllxr1_contact_3m,
  jxl_lxr1contactcnt,
  jxl_lxrhighprovince,
  jxl_bjloancomcnts,
  txfacility_type,
  tx_sbm,
  txmaxent_id,
  tx_operate_system,
  sxfacility_type,
  sx_sbm,
  sxmaxent_id,
  sx_operate_system,
  phoneifbcblack,
  sfzifbcblack,
  risktype91,
  /*
  adjust_bj_score,
  smallAmount_bj_score,
  冰鉴
  */
  br_phnum_yhsl,
  br_phnum_yhdsyq,
  br_phnum_yhbl,
  br_phnum_fysl,
  br_phnum_fydsyq,
  br_phnum_fybl,
  br_idnum_yhsl,
  br_idnum_yhdsyq,
  br_idnum_yhbl,
  br_idnum_fysl,
  br_idnum_fydsyq,
  br_idnum_fybl,
  br_idnum_fysxr,
  br_idnum_fybzxr,
  br_ph_3fyjgs,
  br_ph_3fysqcs,
  br_ph_1fyjgs,
  br_ph_1fysqcs,
  br_id_3fyjgs,
  br_id_3fysqcs,
  br_id_1fyjgs,
  br_id_1fysqcs,
  br_risk_qqnum,
  br_a_risk_qqnum
/*,
ruleId_suspiciousAction
phone_ymd,
phone_xjhm,
phone_xdhy_xyxf,
phone_xdhy_sl,
phone_xdhy_qz,
phone_txxh,
phone_xdhy_p2p,
phone_3m_dtsq_total,
id_taxi_zlqz,
id_taxi_yqwzf,
id_taxi_yqwhc,
id_ymd,
id_xdhy_zxdk,
id_xdhy_cywq,
id_xdhy_cy30,
id_xdhy_xyxf,
id_xdhy_xdh,
id_xdhy_txjy,
id_xdhy_sl,
id_xdhy_shqz,
id_xdhy_qz,
id_xdhy_pqbt,
id_xdhy_mxfzd,
id_xdhy_myfx,
id_xdhy_hzj,
id_xdhy_p2p,
id_sf_qtqz,
id_sf_dyzc,
id_sf_dycz,
id_sf_dk,
id_jd_yqwzf,
id_ga_xid,
id_fy_zx,
id_fy_sx,
id_fy_ja,
id_fr_sx,
id_ds_hyxjjy,
id_ds_sxsj,
id_aqztf,
id_aqgwwl,
id_3m_dtsq_total
白骑士，删掉
*/
from (select
        max(r.create_time),
        r.*
      from rule_in_engine r
      where r.app_no in (31801033100693)
      group by r.app_no) t1, (
                               select
                                 max(r.create_time),
                                 r.*
                               from rule_in_engine_sec r
                               where r.app_no in (31801033100693)
                               group by r.app_no) t2
where t1.app_no = t2.app_no;

select
  adjust_yyhq_bankcard       '线上产品进件输入.盈衍已开户银行卡与嗨钱绑定银行卡是否一致',
  adjust_dd_report           '线上产品进件输入.是否有滴滴报告',
  js_limit_amount            '线上产品进件输入.是否晋商额度用完',
  zjybjqdate_nowsqdatedays   '线上产品进件输入.申请信息.最近一笔结清日期距当前申请日期天数',
  worktime                   '线上产品进件输入.申请信息.总工作年限',
  zjf                        '线上产品进件输入.申请信息.资金方',
  zxlxr_incomisblack         '线上产品进件输入.申请信息.直系亲属手机号是否在我司黑名单',
  zxlxr_incomisdelq          '线上产品进件输入.申请信息.直系亲属手机号是否在我司当前逾期',
  zxlxr_tem_littlephone      '线上产品进件输入.申请信息.直系亲属联系人手机号是否为临时小号',
  zjlxr_black_number         '线上产品进件输入.申请信息.直接联系人中黑名单人数',
  zjlxr_number               '线上产品进件输入.申请信息.直接联系人人数',
  post                       '线上产品进件输入.申请信息.职务',
  dd_id_iphone_number        '线上产品进件输入.申请信息.证件号对应的滴滴手机号',
  graduate_date              '线上产品进件输入.申请信息.预计毕业日期',
  total_amt                  '线上产品进件输入.申请信息.应还总金额',
  bankcode                   '线上产品进件输入.申请信息.银行编码',
  yjq_loan_highest_amount    '线上产品进件输入.申请信息.已结清借款中的最高批复金额',
  total_amt_paid             '线上产品进件输入.申请信息.已还总金额',
  dd_closetravel_percent     '线上产品进件输入.申请信息.已关闭行程占比',
  #yyn_refused '线上产品进件输入.申请信息.一个月之内是否被拒',
  #studystyle '线上产品进件输入.申请信息.学习形式',
  education                  '线上产品进件输入.申请信息.学历',
  ifxj_station               '线上产品进件输入.申请信息.学籍状态是否符合要求',
  xdcp_id                    '线上产品进件输入.申请信息.信贷产品ID',
  nowprovince                '线上产品进件输入.申请信息.现居所在省',
  dd_liveincxdz_number       '线上产品进件输入.申请信息.现居地址在出行地址中出现的次数',
  nowcity                    '线上产品进件输入.申请信息.现居城市',
  wm_ddnumber                '线上产品进件输入.申请信息.外卖订单数',
  ifzd_school                '线上产品进件输入.申请信息.是否重点院校',
  adjust_gjj_report          '线上产品进件输入.申请信息.是否有公积金报告',
  yy_limit_amount            '线上产品进件输入.申请信息.是否盈衍额度用完',
  adjust_new_bankcard        '线上产品进件输入.申请信息.是否新银行卡',
  xl_limit_amount            '线上产品进件输入.申请信息.是否笑脸额度用完',
  xn_limit_amount            '线上产品进件输入.申请信息.是否小诺额度用完',
  adjust_hyc_client          '线上产品进件输入.申请信息.是否为汇有财投资客户',
  adjust_power               '线上产品进件输入.申请信息.是否授权',
  if_allday                  '线上产品进件输入.申请信息.是否全日制',
  hlblack                    '线上产品进件输入.申请信息.是否命中葫芦黑名单',
  ifoldcust                  '线上产品进件输入.申请信息.是否老客户',
  kd_limit_amount            '线上产品进件输入.申请信息.是否口袋额度用完',
  hyc_limit_amount           '线上产品进件输入.申请信息.是否汇有财额度用完',
  huarong_limit_amount       '线上产品进件输入.申请信息.是否华融额度用完',
  haierlimit_amount          '线上产品进件输入.申请信息.是否海尔额度用完',
  ifoldcustlddd              '线上产品进件输入.申请信息.是否滴答贷老客户',
  dfs_limit_amount           '线上产品进件输入.申请信息.是否大丰收额度用完',
  retain_totai_bj            '线上产品进件输入.申请信息.剩余总本金',
  sfz_name_number            '线上产品进件输入.申请信息.身份证组合过其他姓名数',
  sfz_phone_number           '线上产品进件输入.申请信息.身份证组合过其他电话数',
  t1.identityvalid_startdate '线上产品进件输入.申请信息.身份证开始有效期限',
  t1.identityvalid_enddate   '线上产品进件输入.申请信息.身份证结束有效期限',
  t1.identity_no             '线上产品进件输入.申请信息.身份证号码',
  t1.app_amt                 '线上产品进件输入.申请信息.申请金额',
  lxr_incomisblack           '线上产品进件输入.申请信息.亲属联系人手机号是否在我司黑名单',
  lxr_incomisdelq            '线上产品进件输入.申请信息.亲属联系人手机号是否在我司当前逾期',
  qslxr_tem_littlephone      '线上产品进件输入.申请信息.亲属联系人手机号是否为临时小号',
  age                        '线上产品进件输入.申请信息.年龄',
  grade                      '线上产品进件输入.申请信息.年级',
  nation                     '线上产品进件输入.申请信息.民族',
  mfb_facresult              '线上产品进件输入.申请信息.免费包审核结果',
  mfb_score_card             '线上产品进件输入.申请信息.免费包评分卡分数',
  maxent_jin_channel         '线上产品进件输入.申请信息.猛犸进件渠道',
  maxent_id_client_cfnum     '线上产品进件输入.申请信息.猛犸ID重复的客户数',
  t1.app_no                  '线上产品进件输入.申请信息.流水号',
  hitgdelqjd                 '线上产品进件输入.申请信息.老客户历史最高逾期阶段',
  ifdelq                     '线上产品进件输入.申请信息.客户在我司当前是否逾期',
  yh_terms                   '线上产品进件输入.申请信息.客户已还期数',
  craweducation              '线上产品进件输入.申请信息.客户爬取到的学历',
  deqlzncnts                 '线上产品进件输入.申请信息.客户历史逾期还款且产生滞纳金次数',
  ##custtype '线上产品进件输入.申请信息.客户类型',
  ifloan_yjq                 '线上产品进件输入.申请信息.客户贷款是否全结清',
  jzqk                       '线上产品进件输入.申请信息.居住情况',
  jinjian_channel            '线上产品进件输入.申请信息.进件来源',
  lxr2_incomisblack          '线上产品进件输入.申请信息.紧急联系人2手机号是否在我司黑名单',
  lxr2_incomisdelq           '线上产品进件输入.申请信息.紧急联系人2手机号是否在我司当前逾期',
  lxr1_incomisblack          '线上产品进件输入.申请信息.紧急联系人1手机号是否在我司黑名单',
  lxr1_incomisdelq           '线上产品进件输入.申请信息.紧急联系人1手机号是否在我司当前逾期',
  jjk_freedom_score          '线上产品进件输入.申请信息.借记卡.消费自由度分类',
  jjk_trends_score           '线上产品进件输入.申请信息.借记卡.消费趋势得分',
  jjk_cash_score             '线上产品进件输入.申请信息.借记卡.套现模型分类',
  dexfyfxfx_recent_6M        '线上产品进件输入.申请信息.借记卡.近6个月发生大额消费与非消费性支出类交易金额',
  jyjebzc_recent_3M          '线上产品进件输入.申请信息.借记卡.近3个月交易金额标准差',
  jjkconsumer_group_mark     '线上产品进件输入.申请信息.借记卡.高中低消费人群标记',
  jjk_risk_score             '线上产品进件输入.申请信息.借记卡.风险得分分类',
  marry                      '线上产品进件输入.申请信息.婚姻状况',
  hk_date_number             '线上产品进件输入.申请信息.还款期数',
  famprovince                '线上产品进件输入.申请信息.户籍或家庭所在省',
  black_inter_score          '线上产品进件输入.申请信息.黑中介分数',
  appprovince                '线上产品进件输入.申请信息.订单所在省',
  appcity                    '线上产品进件输入.申请信息.订单所在城市',
  dhhm_name_number           '线上产品进件输入.申请信息.电话号码组合过其他姓名数',
  dhhm_sfz_number            '线上产品进件输入.申请信息.电话号码组合过其他身份证数',
  ddalways_travel_city       '线上产品进件输入.申请信息.滴滴最常出行城市',
  ddtravel_total_number      '线上产品进件输入.申请信息.滴滴总行程次数',
  ddsj_average               '线上产品进件输入.申请信息.滴滴司机近3个月月均流水',
  ddsj_resigndate            '线上产品进件输入.申请信息.滴滴司机近3个月月均接单数',
  dd_iphone_sqxxsfyz         '线上产品进件输入.申请信息.滴滴手机号与申请信息是否一致',
  dd_iphone_sfsmrz           '线上产品进件输入.申请信息.滴滴手机号是否实名认证',
  dd_iphone_id_number        '线上产品进件输入.申请信息.滴滴手机号对应的证件号',
  dd_usetime                 '线上产品进件输入.申请信息.滴滴使用时间',
  dd_name_sqxxsfyz           '线上产品进件输入.申请信息.滴滴实名登记的姓名与客户信息是否一致',
  dd_idcard_sqxxsfyz         '线上产品进件输入.申请信息.滴滴实名登记的身份证号码与客户信息是否一致',
  ddsj_czdjrname             '线上产品进件输入.申请信息.滴滴车主登记人姓名同申请信息是否匹配',
  dddyh_total_amt            '线上产品进件输入.申请信息.滴答贷应还总金额',
  dddyh_total_paid           '线上产品进件输入.申请信息.滴答贷已还总金额',
  pay_quantity               '线上产品进件输入.申请信息.当前已结清借款笔数',
  nopay_sm_qualinty          '线上产品进件输入.申请信息.当前未结清的租赁数码数量',
  ifvip                      '线上产品进件输入.申请信息.当前是否VIP客户',
  dd_workincxdz_number       '线上产品进件输入.申请信息.单位地址在出行地址中出现的次数',
  ##producttype '线上产品进件输入.申请信息.产品代码',
  relate_enterprises         '线上产品进件输入.申请信息.查询过该用户的相关企业数量',
  seven_day_vipnum           '线上产品进件输入.申请信息.7天内VIP通过数',
  local_life_time            '线上产品进件输入.评分卡.申请信息.本地居住是否超过1年的检查偏好注记',
  self_call_cnt              '线上产品进件输入.评分卡.聚信立总通话次数',
  all_contact_night          '线上产品进件输入.评分卡.聚信立总深夜联系次数',
  contact_early_morning      '线上产品进件输入.评分卡.聚信立总凌晨联系次数',
  sms_mth_cnt                '线上产品进件输入.评分卡.聚信立通话行为记录数',
  real_max_time              '线上产品进件输入.评分卡.聚信立实名认证最久的日期',
  sms_cnt                    '线上产品进件输入.评分卡.聚信立每个月的月短信条数',
  yunying_call_out_cnt       '线上产品进件输入.评分卡.聚信立联系人属地为运营商的总呼出电话次数',
  phone_stop_time            '线上产品进件输入.评分卡.聚信立长时间关机的检查偏好注记',
  mf_adjust_challenger       '线上产品进件输入.免费包是否挑战者',
  js_ifloan_yjq              '线上产品进件输入.客户是否在晋商已结清',
  service_providers_number   '线上产品进件输入.聚信立.服务商为银行联系次数',
  service_call_number        '线上产品进件输入.聚信立.服务商联系次数',
  fqzps_11                   '线上产品进件输入.反欺诈.直系亲属手机号是否对应2个 或2个以上的身份证号',
  fqzps_10                   '线上产品进件输入.反欺诈.直系亲属手机号是否对应2个或2个以上的申请人姓名',
  fqzps_12                   '线上产品进件输入.反欺诈.现居地址是否对应2个或2个以上身份证号',
  fqzps_09                   '线上产品进件输入.反欺诈.手机号是否对应2个或2个以上 的身份证号',
  fqzps_08                   '线上产品进件输入.反欺诈.手机号是否对应2个或2个以上的申请人姓名',
  fqzps_07                   '线上产品进件输入.反欺诈.身份证号是否对应2个或2个以上的申请人姓名',
  fqzps_06                   '线上产品进件输入.反欺诈.紧急联系人手机号是否对应2个或2个以上的联系人姓名',
  fqzps_05                   '线上产品进件输入.反欺诈.家庭固话是否对应2个或 2个以上身份证号',
  fqzps_04                   '线上产品进件输入.反欺诈.家庭地址是否对应2个或2个以上身份证号',
  fqzps_03                   '线上产品进件输入.反欺诈.单位名称是否对应2个或2个以上单位地址',
  fqzps_02                   '线上产品进件输入.反欺诈.单位电话是否对应2个或2个以上单位名称',
  fqzps_01                   '线上产品进件输入.反欺诈.单位电话是否对应2个或2个以上单位地址',
  xz_information             '线上产品进件输入.法海.﻿行政信息',
  wd_black                   '线上产品进件输入.法海.﻿网贷黑名单',
  sxgg_information           '线上产品进件输入.法海.﻿失信公告',
  ss_information             '线上产品进件输入.法海.涉诉信息',
  all_information            '线上产品进件输入.法海.全部信息',
  ktgg_information           '线上产品进件输入.法海.﻿开庭公告',
  fygg_information           '线上产品进件输入.法海.﻿法院公告',
  cp_information             '线上产品进件输入.法海.﻿裁判文书',
  bzxr_information           '线上产品进件输入.法海.﻿被执行人信息',
  ajlc_information           '线上产品进件输入.法海.﻿案件流程',
  zhima_score                '线上产品进件输入.第三方征信.芝麻评分',
  td_score                   '线上产品进件输入.第三方征信.同盾.同盾评分',
  td_ruleitem                '线上产品进件输入.第三方征信.同盾.同盾命中具体规则项',
  phoneiftdblack             '线上产品进件输入.第三方征信.同盾.手机号是否在同盾黑名单',
  sfziftdblack               '线上产品进件输入.第三方征信.同盾.身份证是否在同盾黑名单',
  phoneifhyblack             '线上产品进件输入.第三方征信.手机号是否在我司黑名单',
  sfzifhyblack               '线上产品进件输入.第三方征信.身份证是否在我司黑名单',
  zx_tdcomcnts               '线上产品进件输入.第三方征信.上海资信.资信显示同贷机构申请次数',
  sfzifzxblack               '线上产品进件输入.第三方征信.上海资信.身份证是否在资信黑名单',
  py_score                   '线上产品进件输入.第三方征信.鹏元.鹏远学籍评分',
  py_smyizhi                 '线上产品进件输入.第三方征信.鹏元.鹏元身份认证是否一致',
  jxl_zdlxrinblack           '线上产品进件输入.第三方征信.聚信立.主动呼叫过的联系人出现在网贷黑名单上为出现',
  phoneifjxlblack            '线上产品进件输入.第三方征信.聚信立.手机号是否在聚信立黑名单',
  ifhavejxl                  '线上产品进件输入.第三方征信.聚信立.是否有聚信立报告',
  sfzifjxlblack              '线上产品进件输入.第三方征信.聚信立.身份证是否在聚信立黑名单',
  jxl_zjloancomcnts          '线上产品进件输入.第三方征信.聚信立.聚信立主叫网贷公司数量',
  jxlzxqs_contact_1w         '线上产品进件输入.第三方征信.聚信立.聚信立直系亲属最近一周联系次数',
  jxlzxqs_contact_1m         '线上产品进件输入.第三方征信.聚信立.聚信立直系亲属最近一月联系次数',
  jxlzxqs_contact_3m         '线上产品进件输入.第三方征信.聚信立.聚信立直系亲属最近三月联系次数',
  jxl_zxcontactcnt           '线上产品进件输入.第三方征信.聚信立.聚信立直系亲属通话记录次数',
  jxlzxqs_6mon_callcnt       '线上产品进件输入.第三方征信.聚信立.聚信立直系亲属前第6月的通话次数',
  jxlzxqs_5mon_callcnt       '线上产品进件输入.第三方征信.聚信立.聚信立直系亲属前第5月的通话次数',
  jxlzxqs_4mon_callcnt       '线上产品进件输入.第三方征信.聚信立.聚信立直系亲属前第4月的通话次数',
  jxlzxqs_3mon_callcnt       '线上产品进件输入.第三方征信.聚信立.聚信立直系亲属前第3月的通话次数',
  jxlzxqs_2mon_callcnt       '线上产品进件输入.第三方征信.聚信立.聚信立直系亲属前第2月的通话次数',
  jxlzxqs_1mon_callcnt       '线上产品进件输入.第三方征信.聚信立.聚信立直系亲属前第1月的通话次数',
  isnewmobile                '线上产品进件输入.第三方征信.聚信立.聚信立推断分析中绑定号码是新号码是否为出现',
  jxl_mobilesm               '线上产品进件输入.第三方征信.聚信立.聚信立手机实名情况',
  jxllxr_contact_1w          '线上产品进件输入.第三方征信.聚信立.聚信立亲属最近一周联系次数',
  jxllxr_contact_1m          '线上产品进件输入.第三方征信.聚信立.聚信立亲属最近一月联系次数',
  jxllxr_contact_3m          '线上产品进件输入.第三方征信.聚信立.聚信立亲属最近三月联系次数',
  jxl_lxrcontactcnt          '线上产品进件输入.第三方征信.聚信立.聚信立亲属通话记录次数',
  jxllxr_6mon_callcnt        '线上产品进件输入.第三方征信.聚信立.聚信立亲属前第6月的通话次数',
  jxllxr_5mon_callcnt        '线上产品进件输入.第三方征信.聚信立.聚信立亲属前第5月的通话次数',
  jxllxr_4mon_callcnt        '线上产品进件输入.第三方征信.聚信立.聚信立亲属前第4月的通话次数',
  jxllxr_3mon_callcnt        '线上产品进件输入.第三方征信.聚信立.聚信立亲属前第3月的通话次数',
  jxllxr_2mon_callcnt        '线上产品进件输入.第三方征信.聚信立.聚信立亲属前第2月的通话次数',
  jxllxr_1mon_callcnt        '线上产品进件输入.第三方征信.聚信立.聚信立亲属前第1月的通话次数',
  jxllxr2_contact_3m         '线上产品进件输入.第三方征信.聚信立.聚信立紧急联系人2最近三月联系次数',
  jxl_lxr2contactcnt         '线上产品进件输入.第三方征信.聚信立.聚信立紧急联系人2通话记录次数',
  jxllxr1_contact_3m         '线上产品进件输入.第三方征信.聚信立.聚信立紧急联系人1最近三月联系次数',
  jxl_lxr1contactcnt         '线上产品进件输入.第三方征信.聚信立.聚信立紧急联系人1通话记录次数',
  jxl_lxrhighprovince        '线上产品进件输入.第三方征信.聚信立.聚信立的联系人所在地区最多的省',
  jxl_bjloancomcnts          '线上产品进件输入.第三方征信.聚信立.聚信立被叫网贷公司数量',
  txfacility_type            '线上产品进件输入.第三方征信.敬庸.提现设备型号',
  tx_sbm                     '线上产品进件输入.第三方征信.敬庸.提现设备唯一识别码',
  txmaxent_id                '线上产品进件输入.第三方征信.敬庸.提现猛犸ID',
  tx_operate_system          '线上产品进件输入.第三方征信.敬庸.提现操作系统',
  sxfacility_type            '线上产品进件输入.第三方征信.敬庸.授信设备型号',
  sx_sbm                     '线上产品进件输入.第三方征信.敬庸.授信设备唯一识别码',
  sxmaxent_id                '线上产品进件输入.第三方征信.敬庸.授信猛犸ID',
  sx_operate_system          '线上产品进件输入.第三方征信.敬庸.授信操作系统',
  phoneifbcblack             '线上产品进件输入.第三方征信.秉诚.手机号是否在秉诚黑名单',
  sfzifbcblack               '线上产品进件输入.第三方征信.秉诚.身份证是否在秉诚黑名单',
  risktype91                 '线上产品进件输入.第三方征信.91征信.91征信风险类型',
  /*adjust_bj_score '线上产品进件输入.冰鉴.是否有冰鉴分',
  smallAmount_bj_score '线上产品进件输入.冰鉴.冰鉴小额火眸分',*/
  br_phnum_yhsl              '线上产品进件输入.百融.通过手机号查询银行(含信用卡)失联',
  br_phnum_yhdsyq            '线上产品进件输入.百融.通过手机号查询银行(含信用卡)短时逾期',
  br_phnum_yhbl              '线上产品进件输入.百融.通过手机号查询银行(含信用卡)不良',
  br_phnum_fysl              '线上产品进件输入.百融.通过手机号查询非银(含全部非银类型)失联',
  br_phnum_fydsyq            '线上产品进件输入.百融.通过手机号查询非银(含全部非银类型)短时逾期',
  br_phnum_fybl              '线上产品进件输入.百融.通过手机号查询非银(含全部非银类型)不良',
  br_idnum_yhsl              '线上产品进件输入.百融.通过身份证号查询银行(含信用卡)失联',
  br_idnum_yhdsyq            '线上产品进件输入.百融.通过身份证号查询银行(含信用卡)短时逾期',
  br_idnum_yhbl              '线上产品进件输入.百融.通过身份证号查询银行(含信用卡)不良',
  br_idnum_fysl              '线上产品进件输入.百融.通过身份证号查询非银(含全部非银类型)失联',
  br_idnum_fydsyq            '线上产品进件输入.百融.通过身份证号查询非银(含全部非银类型)短时逾期',
  br_idnum_fybl              '线上产品进件输入.百融.通过身份证号查询非银(含全部非银类型)不良',
  br_idnum_fysxr             '线上产品进件输入.百融.通过身份证号查询法院失信人',
  br_idnum_fybzxr            '线上产品进件输入.百融.通过身份证号查询法院被执行人',
  br_ph_3fyjgs               '线上产品进件输入.百融.手机号查询近3个月非银机构申请机构数',
  br_ph_3fysqcs              '线上产品进件输入.百融.手机号查询近3个月非银机构申请次数',
  br_ph_1fyjgs               '线上产品进件输入.百融.手机号查询近1个月非银机构申请机构数',
  br_ph_1fysqcs              '线上产品进件输入.百融.手机号查询近1个月非银机构申请次数',
  br_id_3fyjgs               '线上产品进件输入.百融.身份证查询近3个月非银机构申请机构数',
  br_id_3fysqcs              '线上产品进件输入.百融.身份证查询近3个月非银机构申请次数',
  br_id_1fyjgs               '线上产品进件输入.百融.身份证查询近1个月非银机构申请机构数',
  br_id_1fysqcs              '线上产品进件输入.百融.身份证查询近1个月非银机构申请次数',
  br_risk_qqnum              '线上产品进件输入.百融.加入高风险QQ群的个数',
  br_a_risk_qqnum            '线上产品进件输入.百融.加入高风险A类关联QQ群的个数'
/*,
ruleId_suspiciousAction '线上产品进件输入.白骑士.﻿网络关联策略命中规则代码',
phone_ymd '线上产品进件输入.白骑士.﻿手机号比对羊毛党名单',
phone_xjhm '线上产品进件输入.白骑士.﻿手机号比对虚假号码名单',
phone_xdhy_xyxf '线上产品进件输入.白骑士.﻿手机号比对信贷行业信用消费黑名单',
phone_xdhy_sl '线上产品进件输入.白骑士.﻿手机号比对信贷行业失联名单',
phone_xdhy_qz '线上产品进件输入.白骑士.﻿手机号比对信贷行业欺诈名单',
phone_txxh '线上产品进件输入.白骑士.﻿手机号比对通信小号名单',
phone_xdhy_p2p '线上产品进件输入.白骑士.﻿手机号比对命中信贷行业P2P黑名单',
phone_3m_dtsq_total '线上产品进件输入.白骑士.﻿手机号3个月内多头申请数-总数',
id_taxi_zlqz '线上产品进件输入.白骑士.﻿身份证比对租车行业租赁欺诈名单',
id_taxi_yqwzf '线上产品进件输入.白骑士.﻿身份证比对租车行业逾期未支付名单',
id_taxi_yqwhc '线上产品进件输入.白骑士.﻿身份证比对租车行业逾期未还车名单',
id_ymd '线上产品进件输入.白骑士.身份证比对羊毛党名单',
id_xdhy_zxdk '线上产品进件输入.白骑士.﻿身份证比对信贷行业助学贷款逾期名单',
id_xdhy_cywq '线上产品进件输入.白骑士.身份证比对信贷行业曾经逾期未知期限名单',
id_xdhy_cy30 '线上产品进件输入.白骑士.身份证比对信贷行业曾经逾期30天内名单',
id_xdhy_xyxf '线上产品进件输入.白骑士.﻿身份证比对信贷行业信用消费黑名单',
id_xdhy_xdh '线上产品进件输入.白骑士.﻿身份证比对信贷行业信贷黑名单',
id_xdhy_txjy '线上产品进件输入.白骑士.﻿身份证比对信贷行业套现交易名单',
id_xdhy_sl '线上产品进件输入.白骑士.﻿身份证比对信贷行业失联名单',
id_xdhy_shqz '线上产品进件输入.白骑士.﻿身份证比对信贷行业商户欺诈名单',
id_xdhy_qz '线上产品进件输入.白骑士.﻿身份证比对信贷行业欺诈名单',
id_xdhy_pqbt '线上产品进件输入.白骑士.﻿身份证比对信贷行业骗取补贴名单',
id_xdhy_mxfzd '线上产品进件输入.白骑士.﻿身份证比对信贷行业模型分值低名单',
id_xdhy_myfx '线上产品进件输入.白骑士.﻿身份证比对信贷行业冒用风险名单',
id_xdhy_hzj '线上产品进件输入.白骑士.﻿身份证比对信贷行业黑中介名单',
id_xdhy_p2p '线上产品进件输入.白骑士.﻿身份证比对信贷行业P2P黑名单',
id_sf_qtqz '线上产品进件输入.白骑士.﻿身份证比对三方支付其他欺诈名单',
id_sf_dyzc '线上产品进件输入.白骑士.﻿身份证比对三方支付盗用支出名单',
id_sf_dycz '线上产品进件输入.白骑士.﻿身份证比对三方支付盗用操作名单',
id_sf_dk '线上产品进件输入.白骑士.﻿身份证比对三方支付盗卡名单',
id_jd_yqwzf '线上产品进件输入.白骑士.﻿身份证比对酒店行业逾期未支付名单',
id_ga_xid '线上产品进件输入.白骑士.﻿身份证比对公安刑事犯罪名单',
id_fy_zx '线上产品进件输入.白骑士.﻿身份证比对法院执行名单',
id_fy_sx '线上产品进件输入.白骑士.身份证比对法院失信名单',
id_fy_ja '线上产品进件输入.白骑士.﻿身份证比对法院结案名单',
id_fr_sx '线上产品进件输入.白骑士.﻿身份证比对法人失信名单',
id_ds_hyxjjy '线上产品进件输入.白骑士.﻿身份证比对电商行业虚假交易名单',
id_ds_sxsj '线上产品进件输入.白骑士.﻿身份证比对电商行业涉嫌售假名单',
id_aqztf '线上产品进件输入.白骑士.﻿身份证比对安全在逃嫌犯名单',
id_aqgwwl '线上产品进件输入.白骑士.身份证比对安全高危网络行为名单',
id_3m_dtsq_total '线上产品进件输入.白骑士.﻿身份证3个月内多头申请数-总数'*/

from (select t.*, if(@appNo = t.app_no, @rank := @rank + 1, @rank := 1) as rank, (@appNo := t.app_no) app_no_1
      from rule_in_engine t, (select @rank := 0, @appNo := null) b
      where t.app_no in (31801033100693,
                         31801040100047,
                         31801040100072,
                         31801040100089,
                         31801040100109,
                         31801040100180,
                         31801040100197,
                         31801040100208)
      order by t.APP_NO, t.CREATE_TIME desc) t1, (select
                                                     t.*, if(@appNo = t.app_no, @rank := @rank + 1, @rank := 1) as rank,
                                                     (@appNo := t.app_no)  app_no_2
                                                   from rule_in_engine_sec t, (select
                                                                                 @rank := 0,
                                                                                 @appNo := null) b
                                                   where t.app_no in (31801033100693,
                                                                      31801040100047,
                                                                      31801040100072,
                                                                      31801040100089,
                                                                      31801040100109,
                                                                      31801040100180,
                                                                      31801040100197,
                                                                      31801040100208)
                                                   order by t.APP_NO, t.CREATE_TIME desc) t2
where t1.app_no = t2.app_no
      and t1.rank = 1
      and t2.rank = 1;
